### ISSUE TITLE
yaml file

### ISSUE THREAD

**Issue by lgwapnitsky** [InfoSecConsulting/XML_EXPORTER#1]
working in python 3.4.3, i had to modify my database.yml file to read as follows, lest I received errors:

```
#
# Database connection info

host: localhost
drivername: postgres
database: XMLExporter
username: xmlexporter
password: xmlexporter
```

**Comment by asrozar** [comment]
Thanks for the info, I'll look into this.

**Comment by asrozar** [comment]
Added a check to verify that the yml file works, and updated the template to a working template.
